spring.application.name=ZorvynFinance

# Datasource Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

=> => exporting config sha256:c68edf14566077d8ae551e10d12bd6654e3980721ea4173cecf1b388b95cc4c8                                                                                0.0s 
=> => exporting attestation manifest sha256:92de3dfdffee2a6236cc39076de720e7e0bd4337d71ab3265d5a73f3619bdb2c                                                                  0.0s 
=> => exporting manifest list sha256:f13106694738472f7b05dbb75ac85453d55965a784ddb29a4387c626f39c92eb                                                                         0.0s 
=> => naming to docker.io/library/zorvyn-backend:latest                                                                                                                       0.0s 
=> => unpacking to docker.io/library/zorvyn-backend:latest                                                                                                                    0.6s
PS E:\Zorvyn\backend\finance> docker run -p 8080:8080 zorvyn-backend
docker: Error response from daemon: ports are not available: exposing port TCP 0.0.0.0:8080 -> 127.0.0.1:0: listen tcp 0.0.0.0:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Run 'docker run --help' for more information
PS E:\Zorvyn\backend\finance>
